# air.toml config file

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe cmd/server/main.go"
  bin = ".\\tmp\\main.exe"
  full_bin = "APP_ENV=development .\\tmp\\main.exe"
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  exclude_dir = ["assets", "tmp", "vendor", "node_modules", ".git", "bruno", "deployments", "docs", "scripts", "tests"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  follow_symlink = true
  delay = 1000 # ms

[run]
  # This will run your server.
  # If you need to run 'init-db', you can temporarily change this to:
  # cmd = ".\\tmp\\main.exe init-db"
  # and then change it back to run the server.
  cmd = ".\\tmp\\main.exe"
  args = []
  env = []
  port = 8080
  proxy_cmd = ""
  proxy_args = []
  uid = 0
  gid = 0
  autostart = true

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true

